server:
  port: 8086
spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/task
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: ACCOUNT-MANAGEMENT-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
microservice:
  customer: http://CUSTOMER-MANAGEMENT-SERVICE
